###登录 login
POST {{host}}/api/login
Content-Type: application/json

{
  "mobile": "18613030352",
  "password": "123456"
}
> {% client.global.set("token", response.body.data); %}

###查询角色菜单 query_role_menu
POST {{host}}/api/query_role_menu
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "role_id": 3
}
###更新角色菜单 update_role_menu
POST {{host}}/api/update_role_menu
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "role_id": 1,
  "menu_ids": [1,2,3]
}
###角色列表 role_list
POST {{host}}/api/role_list
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "current": 1,
  "pageSize": 10
}
###新增角色 role_save
POST {{host}}/api/role_save
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "remark": "test",
  "role_name": "test",
  "sort": 1,
  "status_id": 1
}
###删除角色 role_delete
POST {{host}}/api/role_delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [100]
}
###更新角色 role_update
POST {{host}}/api/role_update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 7,
  "remark": "test123",
  "role_name": "test123",
  "sort": 1,
  "status_id": 1
}
