// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// createTime：2024/12/25 10:01:11

use rbatis::rbdc::datetime::DateTime;
use serde::{Deserialize, Serialize};

/*
 *岗位信息
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Post {
    pub id: Option<i64>,               //岗位id
    pub post_code: String,             //岗位编码
    pub post_name: String,             //岗位名称
    pub sort: i32,                     //显示顺序
    pub status: i8,                    //部状态（0：停用，1:正常）
    pub remark: String,                //备注
    pub create_time: Option<DateTime>, //创建时间
    pub update_time: Option<DateTime>, //更新时间
}

/*
 *岗位信息基本操作
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
rbatis::crud!(Post {}, "sys_post");

/*
 *根据id查询岗位信息
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
impl_select!(Post{select_by_id(id:&i64) -> Option => "`where id = #{id} limit 1`"}, "sys_post");

/*
 *根据post_code查询岗位信息
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
impl_select!(Post{select_by_code(post_code:&str) -> Option => "`where post_code = #{post_code} limit 1`"}, "sys_post");

/*
 *根据post_name查询岗位信息
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
impl_select!(Post{select_by_name(post_name:&str) -> Option => "`where post_name = #{post_name} limit 1`"}, "sys_post");

/*
 *分页查询岗位信息
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
impl_select_page!(Post{select_page() =>"
     if !sql.contains('count'):
       order by create_time desc"
},"sys_post");

/*
 *根据条件分页查询岗位信息
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
impl_select_page!(Post{select_post_list(post_code:&str, post_name:&str, status:i8) =>"
    where 1=1
     if post_code != null && post_code != '':
      ` and post_code = #{post_code} `
     if post_name != null && post_name != '':
      ` and post_name = #{post_name} `
     if status != 2:
      ` and status = #{status} `
     if !sql.contains('count'):
      ` order by create_time desc"
},"sys_post");
