// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// createTime：2024/12/25 10:01:11

use serde::{Deserialize, Serialize};

/*
 *角色和部门关联表
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RoleDept {
    pub id: Option<i64>, //主键
    pub role_id: i64,    //角色id
    pub dept_id: i64,    //部门id
}

/*
 *角色和部门关联表基本操作
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
rbatis::crud!(RoleDept {}, "sys_role_dept");

impl RoleDept {}
