// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// createTime：2024/12/25 10:01:11

use rbatis::RBatis;
use serde::{Deserialize, Serialize};

/*
 *用户与岗位关联
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct UserPost {
    pub id: Option<i64>, //主键
    pub user_id: i64,    //用户id
    pub post_id: i64,    //岗位id
}

/*
 *用户与岗位关联基本操作
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
rbatis::crud!(UserPost {}, "sys_user_post");

impl UserPost {
    /*
     *通过岗位id查询岗位使用数量
     *author：刘飞华
     *date：2024/12/12 14:41:44
     */
    #[sql("select count(1) from sys_user_post where post_id = ? ")]
    pub async fn count_user_post_by_id(rb: &RBatis, post_id: i64) -> rbatis::Result<i64> {
        impled!()
    }
}
