// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// createTime：2024/12/25 10:01:11

use crate::vo::system::sys_notice_vo::NoticeReq;
use crate::vo::system::sys_notice_vo::NoticeResp;
use crate::vo::system::sys_notice_vo::QueryNoticeListReq;
use rbatis::rbdc::datetime::DateTime;
use rbatis::RBatis;
use rbs::value;
use serde::{Deserialize, Serialize};
/*
 *通知公告表
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Notice {
    pub id: Option<i64>,               //公告ID
    pub notice_title: String,          //公告标题
    pub notice_type: i8,               //公告类型（1:通知,2:公告）
    pub notice_content: String,        //公告内容
    pub status: i8,                    //公告状态（0:关闭,1:正常 ）
    pub remark: Option<String>,        //备注
    pub create_time: Option<DateTime>, //创建时间
    pub update_time: Option<DateTime>, //修改时间
}

impl From<NoticeReq> for Notice {
    fn from(item: NoticeReq) -> Self {
        let mut model = Notice {
            id: item.id,                         //公告ID
            notice_title: item.notice_title,     //公告标题
            notice_type: item.notice_type,       //公告类型（1:通知,2:公告）
            notice_content: item.notice_content, //公告内容
            status: item.status,                 //公告状态（0:关闭,1:正常 ）
            remark: item.remark,                 //备注
            create_time: None,                   //创建时间
            update_time: None,                   //修改时间
        };
        if let None = item.id {
            model.create_time = Some(DateTime::now());
        } else {
            model.update_time = Some(DateTime::now());
        }
        model
    }
}

impl Into<NoticeResp> for Notice {
    fn into(self) -> NoticeResp {
        NoticeResp {
            id: self.id,                         //公告ID
            notice_title: self.notice_title,     //公告标题
            notice_type: self.notice_type,       //公告类型（1:通知,2:公告）
            notice_content: self.notice_content, //公告内容
            status: self.status,                 //公告状态（0:关闭,1:正常 ）
            remark: self.remark,                 //备注
            create_time: self.create_time,       //创建时间
            update_time: self.update_time,       //修改时间
        }
    }
}

/*
 *通知公告表基本操作
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
rbatis::crud!(Notice {}, "sys_notice");

impl Notice {
    /*
     *根据id查询通知公告表
     *author：刘飞华
     *date：2026/07/01 17:49:14
     */
    pub async fn select_by_id(rb: &RBatis, id: &i64) -> rbatis::Result<Option<Notice>> {
        Ok(Notice::select_by_map(rb, value! {"id": id}).await?.first().cloned())
    }

    /*
     *根据条件分页查询通知公告表
     *author：刘飞华
     *date：2026/07/01 17:49:14
     */
    #[html_sql(
        r#"
      <select id="select_by_page">
            `select * from sys_notice`
            <where>
            <if test="req.noticeTitle != '' && req.noticeTitle != null">
                ` and notice_title like concat('%', #{req.noticeTitle}, '%')`
            </if>
            <if test="req.noticeType != 0">
                ` and notice_type = #{req.noticeType}`
            </if>
            <if test="req.status != 2">
                ` and status = #{req.status}`
            </if>
            </where>
      </select>
      "#
    )]
    pub async fn select_by_page(rb: &dyn rbatis::Executor, page_req: &rbatis::PageRequest, req: &QueryNoticeListReq) -> rbatis::Result<rbatis::Page<Notice>> {
        impled!()
    }
}
