// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// createTime：2024/12/25 10:01:11

use rbatis::rbdc::datetime::DateTime;
use serde::{Deserialize, Serialize};

/*
 *部门表
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Dept {
    pub id: Option<i64>,               //部门id
    pub parent_id: i64,                //父部门id
    pub ancestors: String,             //祖级列表
    pub dept_name: String,             //部门名称
    pub sort: i32,                     //显示顺序
    pub leader: String,                //负责人
    pub phone: String,                 //联系电话
    pub email: String,                 //邮箱
    pub status: i8,                    //部门状态（0：停用，1:正常）
    pub del_flag: i8,                  //删除标志（0代表删除 1代表存在）
    pub create_time: Option<DateTime>, //创建时间
    pub update_time: Option<DateTime>, //修改时间
}

/*
 *部门表基本操作
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
rbatis::crud!(Dept {}, "sys_dept");

/*
 *根据id查询部门表
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
impl_select!(Dept{select_by_id(id:&i64) -> Option => "`where id = #{id} limit 1`"}, "sys_dept");

/*
 *分页查询部门表
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
impl_select_page!(Dept{select_page() =>"
     if !sql.contains('count'):
       order by create_time desc"
},"sys_dept");

/*
 *根据条件分页查询部门表
 *author：刘飞华
 *date：2024/12/25 10:01:11
 */
impl_select_page!(Dept{select_page_by_name(name:&str) =>"
     if name != null && name != '':
       where real_name != #{name}
     if name == '':
       where real_name != ''"
},"sys_dept");
