###登录 login
POST {{host}}/api/login
Content-Type: application/json

{
  "mobile": "18613030352",
  "password": "123456"
}
> {% client.global.set("token", response.body.data); %}


###菜单列表 menu_list
POST {{host}}/api/menu_list
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "menu_name": ""
}
###新增菜单 menu_save
POST {{host}}/api/menu_save
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "api_url": "/auth/ping",
  "icon": "FrownOutlined",
  "label": "test4",
  "menu_name": "test4",
  "menu_type": 1,
  "menu_url": "test4",
  "parent_id": 0,
  "remark": "test",
  "sort": 1,
  "status_id": 1
}

###删除菜单 menu_delete
POST {{host}}/api/menu_delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [100]
}
###更新菜单 menu_update
POST {{host}}/api/menu_update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "api_url": "/auth/ping123",
  "icon": "FrownOutlined",
  "id": 35,
  "label": "test4",
  "menu_name": "test4",
  "menu_type": 1,
  "menu_url": "test4",
  "parent_id": 0,
  "remark": "test",
  "sort": 1,
  "status_id": 1
}


