
###登录 login
POST {{host}}/api/login
Content-Type: application/json

{
  "mobile": "18613030352",
  "password": "123456"
}
> {% client.global.set("token", response.body.data); %}

###查询用户菜单 query_user_menu
GET {{host}}/api/query_user_menu
Authorization: Bearer {{token}}


###用户列表 user_list
POST {{host}}/api/user_list
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "current": 1,
  "pageSize": 10,
  "mobile": "18613030352",
  "status_id": 1
}
###新增用户 user_save
POST {{host}}/api/user_save
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "mobile": "18613030351",
  "user_name": "test",
  "remark": "test"
}
###删除用户 user_delete
POST {{host}}/api/user_delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [13]
}
###更新用户 user_update
POST {{host}}/api/user_update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 17,
  "mobile": "18613030351",
  "user_name": "test123",
  "remark": "test123",
  "sort": 1,
  "status_id": 1
}


